recipe_list:
    path:     /{_locale}/recipe
    defaults: { _controller: RecipeBundle:Recipe:getAll , _locale: en }
    requirements:
        _locale: en|es

recipe_add:
    path:      /{_locale}/recipeadd
    defaults:  {  _controller: RecipeBundle:Recipe:add , _locale: en }
    requirements:
        _locale: en|es

recipe_mod:
    path:      /{_locale}/recipemod/{id}
    defaults:  {  _controller: RecipeBundle:Recipe:mod , _locale: en }
    requirements:
        id: \d+
        _locale: en|es

recipe_del:
    path:      /{_locale}/recipedel/{id}
    defaults:  {  _controller: RecipeBundle:Recipe:del , _locale: en }
    requirements:
        id: \d+
        _locale: en|es

recipe_get:
    path:      /{_locale}/recipe{id}
    defaults:  {  _controller: RecipeBundle:Recipe:getById , _locale: en }
    requirements:
        id: \d+
        _locale: en|es

recipe_get_slug:
    path:      /{_locale}/recipe-slug/{slug}
    defaults:  {  _controller: RecipeBundle:Recipe:getBySlug , _locale: en }
    requirements:
        _locale: en|es