recipe_list:
    path:     /receta
    defaults: { _controller: RecipeBundle:Recipe:getAll }


recipe_detail:
    path:      /receta/{slug}
    defaults:  {  _controller: RecipeBundle:Recipe:getBySlug }