services:
#    recipe.example:
#        class: RecipeBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    recipes.by_user:
        class: RecipeBundle\Model\RecipesByAuthor
        arguments: ["@doctrine.orm.entity_manager"]