user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

recipe:
    resource: "@RecipeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
