<?php

namespace RecipeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * recipesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipesRepository extends EntityRepository
{
}
